controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

to_do:
    resource: to_do
    type: directory
    prefix: /todo

notes:
    resource: notes
    type: directory
    prefix: /notes

pesonnes:
    resource: personnes
    type: directory
    prefix: /personnes
