controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_to_do:
    path: /
    controller: App\Controller\ToDoController::indexAction
